# Generated by Django 5.1.2 on 2024-11-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicBackend', '0002_alter_event_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='users/')),
            ],
        ),
        migrations.AlterField(
            model_name='danceclass',
            name='date',
            field=models.TextField(max_length=100),
        ),
    ]
