# Generated by Django 5.1.2 on 2024-11-15 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicBackend', '0005_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], default='pending', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dance_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='BasicBackend.danceclass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'dance_class')},
            },
        ),
    ]
