# Generated by Django 5.1.2 on 2024-11-15 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BasicBackend', '0007_classattendance_danceclass_users_eventattendance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='danceclass',
            old_name='date',
            new_name='days',
        ),
    ]
