# Generated by Django 5.1.2 on 2024-11-15 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicBackend', '0008_rename_date_danceclass_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='danceclass',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructed_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
