# Generated by Django 5.1.2 on 2024-11-15 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicBackend', '0010_alter_classattendance_dance_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classattendance',
            name='dance_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_attendances', to='BasicBackend.danceclass'),
        ),
        migrations.AlterField(
            model_name='danceclass',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructed_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventattendance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to='BasicBackend.event'),
        ),
    ]
