# Generated by Django 5.1.2 on 2024-11-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicBackend', '0011_alter_classattendance_dance_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='danceclass',
            name='level',
            field=models.CharField(choices=[('beginner', 'Begginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
    ]
