# Generated by Django 5.1.2 on 2024-12-04 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('BasicBackend', '0014_alter_danceclass_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassAttendance',
            new_name='DanceClassAttendance',
        ),
        migrations.AlterField(
            model_name='danceclassassignment',
            name='dance_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dance_class_assignments',
                                    to='BasicBackend.danceclass'),
        ),
        migrations.AlterField(
            model_name='danceclassassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='user_dance_class_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EventAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_assignments',
                                   to='BasicBackend.event')),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_event_assignments',
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='users',
            field=models.ManyToManyField(related_name='events', through='BasicBackend.EventAssignment',
                                         to=settings.AUTH_USER_MODEL),
        ),
    ]
